-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contest" add column "arena_switch" boolean
--  not null default 'False';
