-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contest" add column "max_game_time" numeric
--  null default '100';
