-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."honor_application" add column "year" integer
--  not null default '2023';
