-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."contest_room_team" add column "player_codes" text
--  null default '{}';
