-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mentor_info" add column "max_applicants" integer
--  not null default '1';
