-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."mentor_application" add column "chat_confirm" boolean
--  not null default 'false';
