-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."honor_time" add column "activateIn" Integer
--  not null unique default '2024';
